### ISSUE TITLE
Admin - Updated Org Email template

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#107]
**Summary**
This is the email sent to an organisation in case a super admin changes their email address.

**Copy**
Subject: Your Cost of Living email address was reset
Body: 

> Good news! Your Cost of Living email address was reset. 
> 
> To login using this email address, please reset your password at the following URL: _col-helper.co.uk/pwd-reset-url_ 
>  
> Best wishes,
> The Cost of Living Helper Team
> 

**Acceptance Criteria**
**Front End**
- [ ] Trigger the reset password flow
- [ ] ...

**Back End**
- [ ] ...
- [ ] ...

**Comment by Israa91** [comment]
Hey @egasparini ,can you provide email copy, please.

**Comment by egasparini** [comment]
@maggiehoughton could you please double check just to make sure the copy for this email is fine?
Thanks!

**Comment by maggiehoughton** [comment]
All good!
