### ISSUE TITLE
Customisable colours don't always relate to their labels

### ISSUE THREAD

**Issue by remaininlight** [yalla-coop/cost-of-living-support#118]
The page for customising colours of the app was built in this issue:
https://github.com/yalla-coop/cost-of-living-support/issues/33

It works but the names of the colours don't seem to always correspond to what they refer to. For example, here all the background colours have been set to orange and all the text colours to white:
<img width="633" alt="image" src="https://user-images.githubusercontent.com/4106946/204566483-9d82cfdb-595b-44d0-bba6-02c24d69d13b.png">

But this is not reflected in what is displayed. Much of the text seems to be taking a background colour: 
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/4106946/204566293-466b9cc4-0e1c-45b3-a0f2-c0f4493a8d04.png">

__Front__
- [ ] The text colours in 'Add/update brand colours' change the colour of text
- [ ] The background colours in 'Add/update brand colours' change the colour of backgrounds

**Comment by egasparini** [comment]
Approach discussed with @jema28 & @fadeomar:
- [ ] Revert changes done in #33 both for CoL & UC
- [ ] On CoL: create separate labels for: 
   - [ ] Header -> the background colour changes, matching the `Main header background colour`. 
   - [ ] Section / Header -> we have 5 sections, and each one should have a customisable background colour and text colour. The background colour also changes the colour of the little arrow icon on the landing page.

![Image](https://user-images.githubusercontent.com/55511970/205031759-bb7e812e-d047-4139-9cd8-7ed9e1779b6b.png)
![Image](https://user-images.githubusercontent.com/55511970/205031455-dd616b88-b204-4392-862a-ddcaffd14274.png)

- [ ] If organisations create new sections, the colours repeat; so the 6th section will use the Main colour background & text, and the 7th section will use the Secondary background colour & text.
