### ISSUE TITLE
Change the HTML page title

### ISSUE THREAD

**Issue by remaininlight** [yalla-coop/cost-of-living-support#119]
The page title currently reads:
<img width="238" alt="image" src="https://user-images.githubusercontent.com/4106946/204568160-1ae1d6fb-8f35-442d-9f0c-5c136cd2763d.png">

This should be changed to match the project, possibly to 'Cost of Living Support'. @jema28 I'm not sure why the Universal Credit Support title is in block caps? Do you think this text works for Cost of Living Support?

### Technical Acceptance Criteria:

__Front__
- [x] Change HTML page title to be 'Cost of Living Support'

**Comment by jema28** [comment]
Hey @remaininlight I wasn't aware of this, I don't think either need to be in caps
