### ISSUE TITLE
Admin - Stats - Store sign up date

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#12]
**Summary**

We want to store when an organisation signs up with us.

**Wireframes**
Desktop: https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=4687%3A35692&t=5MsCmX9kzAuVR4Kn-4
Mobile: 

**Acceptance Criteria**
**Front End**
- [x] ...
- [x] ...

**Back End**
- [x] ...
- [x] ...

**Comment by jema28** [comment]
Hey @egasparini, I've added it on this page https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=4653%3A18026

**Comment by fadeomar** [comment]
this issue is covered in PR https://github.com/yalla-coop/cost-of-living-support/pull/105
