### ISSUE TITLE
Add/update brand colours presents a blank page

### ISSUE THREAD

**Issue by cemalokten** [yalla-coop/cost-of-living-support#132]
- Priority-2 (Important e.g. Staff cannot access correct information or data / Users cannot add a spend activity)

**Describe the bug**
Logging in as an organisation, the Add/update brand colours page does not load

![image](https://user-images.githubusercontent.com/60609268/205706369-ced58637-a222-44f6-aad4-318425165499.png)

**Team - do not edit**
@thejoefriel

**Comment by fadeomar** [comment]
hey @cemalokten can't replicate this 
here is a loom in my story : https://www.loom.com/share/7d6ab86fb4394eb7a86f990e63a14cee

can you check again please

**Comment by cemalokten** [comment]
> hey @cemalokten can't replicate this here is a loom in my story : https://www.loom.com/share/7d6ab86fb4394eb7a86f990e63a14cee
> 
> can you check again please

Hey @fadeomar, the issue seems to only be present on new accounts, it works for me using admin1@hyde... but not a new account.
