### ISSUE TITLE
CoL Deployment

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/cost-of-living-support#15]
### Summary
This issue is to cover all those loose ends we always need to do

### Criteria
@remaininlight @RamyAlshurafa can you add more here when you look at the sizing please?

- [x] Deploy CoL to new domain [col-helper.co.uk](http://col-helper.co.uk/) (I've forwarded the email to Mark and Ramy in case you need to sort anything with Maggie beforehand)
- [x] Ensure all third party solutions are set up and working with the production version
    - [x] Google Analytics
    - [x] Hotjar
    - [x] Sendgrid
    - [x] Better Uptime
- [x] ReadMe up to date 
- [x] DB schema up to date in Technical Design doc

**Comment by remaininlight** [comment]
Hi @maggiehoughton, I'm deploying the Universal Credit Support staging but need to add a database to complete the deployment. Are you around today or tomorrow to add a 'Heroku Postgres Mini' here please:
https://dashboard.heroku.com/apps/hyde-dev/resources

Let me know if you're around for a call about it and I can guide you

**Comment by remaininlight** [comment]
Great, thanks @maggiehoughton - does 9:30 work for you? Have sent you a calendar invite
