### ISSUE TITLE
fix copy bugs from bugs report

### ISSUE THREAD

**Issue by fadeomar** [yalla-coop/cost-of-living-support#157]
- [x] [2](https://www.notion.so/yallacooperative/1e493acd14934b7a83b57199aea68b03?v=d01b8364d9d147709e6c01dfbe26f028&p=0aada66d78904edcbebf5a500525221c&pm=s): First section ‘Talk to your landlord and mortgage provider needs to read: If you're struggling to pay your rent and/or mortgage speak to your landlord and  mortgage provider as soon as possible, even if you haven't missed a payment yet. There are often many things they can do to help you.
  - [x] [3](https://www.notion.so/yallacooperative/1e493acd14934b7a83b57199aea68b03?v=d01b8364d9d147709e6c01dfbe26f028&p=2671c086dcb74947b77c67af81fe24fa&pm=s): The Help button copy directs you to the UC help helpline It needs to go to Moneyhelper: If you’d like to talk to someone, call [Money Helper](tel:0800%20138%207777)
  - [x] [4](https://www.notion.so/yallacooperative/1e493acd14934b7a83b57199aea68b03?v=d01b8364d9d147709e6c01dfbe26f028&p=10790d2a660f4baeb7c156d1d12673a2&pm=s): The ‘Stuck?’ copy directs you to the UC help helpline It needs to go to Moneyhelper: If you’d like to talk to someone, call [Money Helper](tel:0800%20138%207777)
  - [x] [5](https://www.notion.so/yallacooperative/1e493acd14934b7a83b57199aea68b03?v=d01b8364d9d147709e6c01dfbe26f028&p=a9b6274ec7b24a63874917be02581bc2&pm=s): This sentence between the section headline and the ‘read more’ button can be removed as it’s superfluous: You know how much is going in and out but if you need a hand, we can help you work it out.
  - [x] [10](https://www.notion.so/yallacooperative/1e493acd14934b7a83b57199aea68b03?v=d01b8364d9d147709e6c01dfbe26f028&p=ce7d0698237d42a8979f2e2623737975&pm=s): Needs ? after Feeling stressed or overwhelmed
  - [x] [11](https://www.notion.so/yallacooperative/1e493acd14934b7a83b57199aea68b03?v=d01b8364d9d147709e6c01dfbe26f028&p=4a5cf7ee5e3a405caea5d333928fa039&pm=s): The copy is wrong on the ‘edit account details’ page. It needs to read: Below you can edit the details of your account; add a back up email account; change your unique link, or delete the account.

**Comment by egasparini** [comment]
@fadeomar - this isn't fixed:
- [ ] [2](https://www.notion.so/yallacooperative/1e493acd14934b7a83b57199aea68b03?v=d01b8364d9d147709e6c01dfbe26f028&p=0aada66d78904edcbebf5a500525221c&pm=s): First section ‘Talk to your landlord and mortgage provider needs to read: If you're struggling to pay your rent and/or mortgage speak to your landlord and mortgage provider as soon as possible, even if you haven't missed a payment yet. There are often many things they can do to help you.

Can you please take a look?
