### ISSUE TITLE
Text doesn't fit properly on content edit

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#167]
See screenshot:

![Image](https://user-images.githubusercontent.com/55511970/206404005-d903836e-59b2-4e8e-aa2c-f0786b5119f3.png)

There's lots of space on the page, we should make sure that the text fits without breaking up.

**Comment by egasparini** [comment]
This is still not right @fadeomar.
The edit button & rearrange button are now fully visible, but they should be aligned on the right. See Maggie's screenshot
![col admin section untidy](https://user-images.githubusercontent.com/55511970/207414426-1057f64d-eac8-4e08-b4c9-a8c959d2420c.JPG)

Can you please take a look?

**Comment by cemalokten** [comment]
Fixed in #197
