### ISSUE TITLE
Copy changes

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#169]
- [x] Dashboard > Add/Update content page: The copy needs to read: ‘Drag the sections to reorder the content that your clients see, add a new section or hide any sections that isn't relevant to your organisation.’
- [x] Accessibility > Change font >	Instead of ‘none’ say ‘default’
- [x] Accessibility > Change font > The change font heading reads ‘text to speech’ instead of 'Change font'
![Image](https://user-images.githubusercontent.com/55511970/206405451-9e48002d-32da-4afe-82ab-00fa2cbcefd1.png)
 
- [x] Landing page > Inconsistent copy;  change ‘Maximising your income’ to ‘Maximising my income’ 

![Image](https://user-images.githubusercontent.com/55511970/206405080-48a50acd-15c5-44ca-a7be-14be2a94261d.png)

- [x] https://staging.col-helper.co.uk/hyde/sections/3 > Access "Get help from your local authority or DWP" > Copy on Helpful resources button ("Living in squeezed income") is wrong, it should read: ‘Living on a squeezed income’ 

![Image](https://user-images.githubusercontent.com/55511970/206405286-d6fb3110-b460-4544-ad18-8452ef6fbb35.png)

**Comment by egasparini** [comment]
@fadeomar / @RamyAlshurafa two of the items in this task aren't fixed: 
- [ ] Landing page > Inconsistent copy; change ‘Maximising your income’ to ‘Maximising my income’
- [ ] https://staging.col-helper.co.uk/hyde/sections/3 > Access "Get help from your local authority or DWP" > Copy on Helpful resources button ("Living in squeezed income") is wrong, it should read: ‘Living on a squeezed income’

Can you please take a look?

**Comment by cemalokten** [comment]
Fixed
![image](https://user-images.githubusercontent.com/60609268/207588309-ab5d67c6-5d10-4d5c-9bea-2613917783f0.png)
