### ISSUE TITLE
Links in sections that I have added do not work. 

### ISSUE THREAD

**Issue by fadeomar** [yalla-coop/cost-of-living-support#172]
**Bug link:** [15](https://www.notion.so/yallacooperative/1e493acd14934b7a83b57199aea68b03?v=d01b8364d9d147709e6c01dfbe26f028&p=6ad835bab5cf45839850d27f108d1eff&pm=s)

**Description**: Links in sections that I have added do not work. 

**Vedio**: [https://www.loom.com/share/ad5d750d1f0f4310901fc4b422da7632](https://www.loom.com/share/ad5d750d1f0f4310901fc4b422da7632)

**Comment by egasparini** [comment]
@fadeomar see @maggiehoughton 's comment in notion: https://www.notion.so/15-6ad835bab5cf45839850d27f108d1eff?d=9ef24d21a9514c178680bd9cf7e6267c 

In a nutshell, the links she embeds don't work. You can also see a loom video here: https://www.loom.com/share/a0676b7a674d474c9880e30dec884ca7

Can you please take a look?

**Comment by cemalokten** [comment]
I've checked this and it works now

**Comment by egasparini** [comment]
@cemalokten this only works if you enter the URL including `https://`. If you just write `www.*` it doesn't work. Can we make it work in both cases? Is that complex?
See for example the tips of "Erica test section" here: https://staging.col-helper.co.uk/hyde/sections/11
The first URL is configured as `https://` and it works. The second one only has `www.` and gives the following console errors:
![Screenshot 2022-12-14 at 18 30 06](https://user-images.githubusercontent.com/55511970/207665997-bd3e5f7b-a34d-4a92-8ef5-5deb57da1862.png)

I created this section with the superadmin account, if you want to see how I configured it in the tool. Here's a screenshot as well for reference:
![Screenshot 2022-12-14 at 18 34 38](https://user-images.githubusercontent.com/55511970/207667066-939f7e4c-64df-4b5a-a9e4-90d1738e9b46.png)

Thanks!

**Comment by cemalokten** [comment]
@egasparini There are two issues here, the first one has been resolved. The second is a separate issue that is to do with the Markdown editor we are using, at this time I think it would require a reasonable amount of work to enable users to enter URL's without the correct prefix, ie. `http://`

For now, perhaps this can be something that is considered during the review process of new content?

**Comment by egasparini** [comment]
@cemalokten alright if it's a big thing to solve, let's add some copy below **Tips** _(optional)_ that reads something like: "When adding a URL, remember to enter the full address, e.g. https://www.mywebsite.com". 
If you have a better way of phrasing this, be my guest :)
