### ISSUE TITLE
Change email to coldigital@hyde-housing.co.uk on dashboard

### ISSUE THREAD

**Issue by cemalokten** [yalla-coop/cost-of-living-support#181]
Change email to coldigital@hyde-housing.co.uk on dashboard 

https://www.notion.so/yallacooperative/29-beb4599571b64725b413ce0c8716cf8e

**Team - do not edit**
@thejoefriel

**Comment by egasparini** [comment]
@cemalokten - This is not fixed.
When I hover over the email on CoL, I see that behind it there's still the old email address.
![Screenshot 2022-12-15 at 13 19 49](https://user-images.githubusercontent.com/55511970/207858516-a7a3bd66-b42c-48a7-85ed-0b546ef95d55.png)

Moreover, when I click on the box with the email address nothing happens and I am not able to select the email address to copy and paste.
