### ISSUE TITLE
Update Privacy Policy & T&C links

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#199]
Maggie provided us with the URLs for Privacy Policy and Terms & Conditions. 
Please, add them to the sign up page: https://staging.col-helper.co.uk/admin/signup
![Image](https://user-images.githubusercontent.com/55511970/207820879-5356cada-827b-4405-b419-99107c297d24.png)

Privacy Policy URL: https://www.hyde-housing.co.uk/privacy/hyde-foundation-privacy/
T&Cs URL: https://www.hyde-housing.co.uk/privacy/hyde-foundation-privacy/hyde-foundation-digital-tools-terms-of-use/ (we are aware that this page is currently returning a 404, Hyde will fill in the content at a later stage)

**Comment by cemalokten** [comment]
Will add to cookiebanner #198
