### ISSUE TITLE
Set up Google Analytics for Cost of Living Helper

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/cost-of-living-support#20]
**Summary**
We need to track the usual activity through Google Analytics on the Cost of Living tool

**Comment by fadeomar** [comment]
I've created a new app in hyde google analytics account for the COST OF LIVING APP and added the project id to the admin sheet https://github.com/yalla-coop/universal-credit-support/issues/1, but still need to update the website URL to the real one when its ready

**Comment by remaininlight** [comment]
@fadeomar Production URL is:
https://col-helper.co.uk/

Staging is:
https://staging.col-helper.co.uk/

**Comment by fadeomar** [comment]
hey @maggiehoughton I've requested an auth code for your phone trying to setup google analytics can you please provide me that code please 
![image](https://user-images.githubusercontent.com/39485495/207639286-feca5591-6068-4360-a335-dbd3a2d46543.png)

**Comment by maggiehoughton** [comment]
hi @fadeomar I've disabled two factor auth and also said your device is safe- try now?

**Comment by maggiehoughton** [comment]
I didn't get a code, it just said they had stopped someone from logging in.

**Comment by fadeomar** [comment]
hey @maggiehoughton  I'll try again now

**Comment by fadeomar** [comment]
this is working now for production
![image](https://user-images.githubusercontent.com/39485495/208654963-7037c316-bc59-4bad-8ac8-27d51bc908da.png)
