### ISSUE TITLE
Change Font doesn't work correctly

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#200]
See Loom recording: https://www.loom.com/share/abf077ad1ad74668b7cae682b016eaee 

In a nutshell; when changing the font to Heebo or Roboto, not all text on the page is updated to the new font.
Also, on UC Helper we should rename "none" to "default" and show it in the default font.

**Comment by cemalokten** [comment]
Hi @egasparini, I agree this is confusing. Having looked into it I can see that all headings by default are 'new-hero' and all other text is 'Heebo'. So when a use selects 'Heebo' it only translates the headings, as everything else is already 'Heebo', which explains why you see no change. 

Also, Roboto and Heebo are almost identical, so offer no real value in being options.
![image](https://user-images.githubusercontent.com/60609268/207879814-42c27c7f-d218-45e7-9478-bbec68046c5b.png)

How would you like me to proceed with this @thejoefriel ? 

I can replace Heebo and Roboto with a serif font like (https://fonts.google.com/specimen/Roboto+Slab?preview.text=Example&preview.text_type=custom&category=Serif) so the options are:

- Default (Heebo / New Hero) - **Sans serif**
- Roboto Slab - **Serif**
- Comic Neue - **Handwriting**

**Comment by egasparini** [comment]
@cemalokten - I didn't realize that Heebo was already the font we were using. That's fine then. 
I would keep both Roboto and Heebo, as they were requested specifically for accessibility, even though they are very similar. 
As long as the functionality works - let's not change it. Just, I had the impression that something was broken, but I'm glad that's not the case. I would suggest we close this task.

**Comment by egasparini** [comment]
@cemalokten on UC Helper, the default font is still called "none" in the dropdown. We need to change that to say "default" instead, in the default font, just like we do on CoL. Can you please take a look?

**Comment by cemalokten** [comment]
@egasparini I believe this is the same issue as the footer comment still being present, we need to redeploy the latest version. This change was made and merged here #783599
