### ISSUE TITLE
Create CoL Super admin account

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#203]
Set up a super admin account for Cost of Living using this email address:

- coldigital@hyde-housing.co.uk with hydefoundation@hyde-housing.co.uk as backup.

**Comment by cemalokten** [comment]
@RamyAlshurafa What is the best way to do this? In the dummy-prod data or signing up and then changing the account role in the prod DB?

**Comment by RamyAlshurafa** [comment]
They should be in the initial build for the production DB

**Comment by remaininlight** [comment]
Thanks for the help @RamyAlshurafa! 

@egasparini Cost of Living production now has coldigital@hyde-housing.co.uk as a super admin. Please would you ask them to do a password reset on that email and they should be able to login
