### ISSUE TITLE
Running costs overview

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#205]
**Summary**

On the google sheet with accounts & credentials:
- [x] add a description of each tool to explain at a high level what it's for 
- [x] specify how much each tool costs.
- [x] add overview of additional costs if we wanted to have DB rolling backup

**Comment by remaininlight** [comment]
@egasparini What do you mean by DB rolling back please? Does it refer to restoring database backups?

**Comment by egasparini** [comment]
> @egasparini What do you mean by DB rolling back please? Does it refer to restoring database backups?

Yes I think so - right @thejoefriel?

**Comment by thejoefriel** [comment]
Yes @remaininlight @egasparini rolling backups for the database so data is protected in the case of data loss. Would be good to know the cheapest level Heroku allows it

**Comment by remaininlight** [comment]
Updated spreadsheet here
https://docs.google.com/spreadsheets/d/1gHzpjitlXnoywgDoL8hd_pgn4Mo64RwuwRWFFkKYX2E/edit#gid=0
