### ISSUE TITLE
UC Helper > Remove footer placeholder text

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#206]
I assume that this shouldn't be there?? 

![Image](https://user-images.githubusercontent.com/55511970/207862459-649be7f3-2f7c-46a4-90be-299ea420b5e4.png)

**Comment by cemalokten** [comment]
@RamyAlshurafa @thejoefriel do we want the social footer from COL on UC?

**Comment by egasparini** [comment]
@cemalokten I can't see this on any of the [UC Helper designs](https://www.figma.com/file/2b1vIUlRczjuwhWr9cE9OY/Wireframes?node-id=1787%3A3575&t=sT91yDu10hDUeNVm-0), so I would say we don't need it.

**Comment by egasparini** [comment]
@cemalokten this task is marked as Done, but I still see the same copy in the UC Helper footer. Can you please double check?


![Image](https://user-images.githubusercontent.com/55511970/208388483-c8147c4c-8003-4f82-b475-9e9f4dad129e.png)
