### ISSUE TITLE
UC Helper > Can't change phone number

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#207]
**Summary**
On UC Helper when I go to https://hyde-dev.herokuapp.com/admin/customise-resources 
and add a phone number in the first field, such as in the screenshot, I get a "Forbidden" error:

![Image](https://user-images.githubusercontent.com/55511970/207864504-8900d432-1689-4dff-b046-e923261464ac.png)

**Comment by remaininlight** [comment]
This looks like it's related to the other database issues, hopefully it will be sorted when the database works

**Comment by remaininlight** [comment]
Database is back online but this is still broken

**Comment by cemalokten** [comment]
@RamyAlshurafa Are you able to help with this?

**Comment by RamyAlshurafa** [comment]
sure, @cemalokten will fix it on Sunday
