### ISSUE TITLE
UC Helper > Superadmin > Add/update content

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#212]
**Summary**
If I login on UC Helper as superadmin and click on `Add/update content` https://hyde-dev.herokuapp.com/admin/content
then select for example `Manage steps` and any of the steps, I don't see any of the content on the page. When I scroll all the way down, I see **an internal server error occurred**.
Maybe this is related to the DB issue we were having earlier this week, but I want to flag it just in case it's something else. 

![Image](https://user-images.githubusercontent.com/55511970/207886312-ba80e0e4-6c9e-4d54-86d7-b56451ff74da.png)

**Comment by remaininlight** [comment]
This looks like a database issue, hopefully it will be sorted when the database setup works

**Comment by fadeomar** [comment]
GET /api/steps/1 500 96.521 ms - 106
[1] GET /api/organisations/1 304 87.514 ms - -
[1] error: column reference "id" is ambiguous

**Comment by remaininlight** [comment]
@egasparini Database is back online, content is displaying


![Image](https://user-images.githubusercontent.com/4106946/207919037-60d803c1-7fed-4f58-a811-2d745e599428.png)

**Comment by RamyAlshurafa** [comment]
as @fadeomar commented, the error still persists
