### ISSUE TITLE
UC Helper > Issue with displaying custom logo

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#216]
**Steps to reproduce**

1. Login to https://hyde-dev.herokuapp.com/admin/dashboard as admin1@hyde.co.uk
2. Click on [Add/update brand colours](https://hyde-dev.herokuapp.com/admin/customise)
3. Upload a logo, e.g. this one 

![Image](https://user-images.githubusercontent.com/55511970/208415316-f7bdfad8-0b8c-4a4b-a2eb-33ab04dd37fc.png)

**Actual result**
The logo doesn't display correctly either on the dashboard or on the UC Helper front end.

![Image](https://user-images.githubusercontent.com/55511970/208415482-8d286a7b-0aaf-4c9c-955d-8ba6af3d773b.png)

![Image](https://user-images.githubusercontent.com/55511970/208415564-9943ef9f-0abb-43d3-bdac-e9ada86ef29c.png)
 

**Expected result**
The logo is displayed correctly both on the dashboard and UC Helper front end, just like we do for CoL.

**Comment by remaininlight** [comment]
@fadeomar Did we resolve this before Christmas? Was this the one I changed the CORs permissions on the bucket for and it worked? @egasparini Says it's not working now on Cost of Living though

**Comment by remaininlight** [comment]
Think this is related to CORs issues we're experiencing with S3 buckets, also tracking here:
https://github.com/yalla-coop/shannon-trust/issues/1624

**Comment by egasparini** [comment]
@dupreesi I had to reopen this cause it seems broken again on staging... can you and @remaininlight take a look after the team activity please?
