### ISSUE TITLE
UC > Right to Left language > bug with phone numbers

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#223]
**Summary**

Same issue that we had on CoL: in right to left languages, numbers should still be written left to right. 
![Image](https://user-images.githubusercontent.com/55511970/211620514-2adacbcc-7394-4e87-812d-5c529b6d5545.png)

See #179 for reference

**Comment by egasparini** [comment]
@cemalokten this task has been in Pending Review for a while and I don't see a PR connected to the task. 
Can you please share what the status is? I see that the fix is not on staging.

**Comment by cemalokten** [comment]
See PR here : https://github.com/yalla-coop/universal-credit-support/pull/263
