### ISSUE TITLE
UC Helper - Store statistics/hook into google analytics

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#23]
**Summary**
On the dashboard of the Universal Credit tool we want to show some statistics/analytics.

**Wireframes**
Desktop: https://www.figma.com/file/2b1vIUlRczjuwhWr9cE9OY/Wireframes?node-id=1911%3A8188

**Acceptance Criteria**

**Front End**
- [ ] ...
- [ ] ...

**Back End**
- [ ] ...
- [ ] ...

**Comment by dupreesi** [comment]
@thejoefriel do we need to set up GA for both projects? Just because respective label (CoL + UC) got removed ...

**Comment by thejoefriel** [comment]
I guess it would make sense to do it on both yeah but this issue as a minimum was more just to tie in the UC helper ones as that was a higher priority
