### ISSUE TITLE
SENTRY: language code is missing

### ISSUE THREAD

**Issue by RamyAlshurafa** [yalla-coop/cost-of-living-support#230]
invalid input value for enum language_codes: "bs"

https://sentry.io/share/issue/edb6703b4a6045a79f232532bd46889d/

**Comment by cemalokten** [comment]
The `bs` language code is for Bosnian, which translates without any issues. The `bs` language code is the same in all of the following file:

```
client/src/constants/data-types.js
client/src/i18n.js
server/src/constants/data-type.js                                                                                            
server/src/database/init/types.sql
```

I'm not sure where the issue is as the `bs` is the same throughout.

**Comment by RamyAlshurafa** [comment]
Yeah not sure why this happened, just checked and found `bs` in the list in the DB and there is a row for it in the translations table, will close and we can re-open it if it happens again
