### ISSUE TITLE
CoL - Issues with email templates

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#234]
**Summary**
This task is about fixing a few issues related to email templates.

### 1. Sign up details email
This refers to #22
- [x] `You have successfully created created an account for the  Cost of living helper` it says created twice and there are two spaces before the word Cost. 
- [x] Check the URL to the admin login page, it's mentioned twice in the copy like this: **[col-helper.co.uk](http://col-helper.co.uk/)/admin/login** so it's not going to open the login page if you click on it
- [x] In the last paragraph the link to email [CoLdigital@hyde-housing.co.uk](mailto:CoLdigital@hyde-housing.co.uk) is in a different font than the rest 
- [x] The signature at the end is incorrect. It reads `The Universal Credit Support Helper Team` instead of `The Cost of Living Helper Team`

[Yalla Cooperative Mail - Sign up details.pdf](https://github.com/yalla-coop/cost-of-living-support/files/10425539/Yalla.Cooperative.Mail.-.Sign.up.details.pdf)

### 2. Section Rejected
This refers to #32 , specifically to the use case when a section is **rejected**
- [x] The reason for rejection is not displayed in the email. See for example https://staging.col-helper.co.uk/erica/sections/16 was rejected with a reason, but it's not in the body of the email 

[Yalla Cooperative Mail - Section rejected.pdf](https://github.com/yalla-coop/cost-of-living-support/files/10425639/Yalla.Cooperative.Mail.-.Section.rejected.pdf)

### 3. Superadmin review new section
This refers to #30 

- [x] to test this you need to have a super admin account linked to an email address you can access
- [x] when you submit a section for review, the super admin should receive an email notification, but the email doesn't come through

**Comment by RamyAlshurafa** [comment]
done @egasparini

**Comment by egasparini** [comment]
@RamyAlshurafa the Sign up details email still says created twice and has two spaces before `Cost of Living`... 
Can you please double check?

![Image](https://user-images.githubusercontent.com/55511970/213412635-5fd6c5e1-c406-494e-a11b-0e86c855d0ea.png)

**Comment by egasparini** [comment]
Also about **3. Superadmin review new section** the email (#30) doesn't come through.

**Comment by egasparini** [comment]
I just tested **3. Superadmin review new section** and it works correctly. 
Last things that need to be fixed are the below:

**Cost of Living**
- Sign up details email: in the first line it repeats “created” twice
- Account approved & rejected emails: the link to the admin dashboard is wrong - it’s http://cost-of-living-helper.com/admin/login instead of col-helper.co.uk/admin/login 
- Password reset email: contact email should be coldigital@hyde-housing.co.uk

**UC Helper:**
- Sign up details email: in the first line it repeats “created” twice
- Password reset email: contact email should be UCdigital@hyde-housing.co.uk

**Comment by RamyAlshurafa** [comment]
Hi @egasparini 
the issues are now fixed 🤞
