### ISSUE TITLE
UC Helper - Issues with email templates

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#236]
**Summary** 
Here I'm listing Maggie's feedback after testing the UC Helper email functionality

### Profile approved email
- [x] link to admin link is wrong. it reads **https://uc-helper.co.uk//admin/login** (one / too many before admin)
- [x] The font is not the same in the whole email. See screenhot:
![Image](https://user-images.githubusercontent.com/55511970/212726386-71060393-3c4d-48a8-9211-f9368b7bf93a.jpg)

### Account creation email
- [x] Some sentences are in a different font. See screenshot below.
- [x] link to admin link is wrong. it reads **https://uc-helper.co.uk//admin/login** (one / too many before admin)
- [x] email address is incorrect. It should be `UCdigital@hyde-housing.co.uk` 
![Image](https://user-images.githubusercontent.com/55511970/212726387-1601e583-2072-4160-9034-4c033d6bf6bb.jpg)

**Comment by RamyAlshurafa** [comment]
done now @egasparini if you can check please
