### ISSUE TITLE
Ensure white label variations are working

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#24]
**Summary**
As on the UC helper right now you, when you go to the unique slug url of an organisation you get their custom details, brand colours and links. This issue is to ensure that the updates we've made (e.g. being able to select more brand colours, the different content that is unique to each organisation) are all getting pulled in and displayed properly. 

The core work might actually be covered by the other issues e.g. 
yalla-coop/cost-of-living-support#33 
yalla-coop/cost-of-living-support#45 

But I suggest we leave this as an issue for the end to ensure everything works correctly and if not, to make fixes

**Wireframes**
Mobile: https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=4741%3A17582

**Acceptance Criteria**
**Front End**
- [x] ...
- [x] ...

**Back End**
- [x] ...
- [x] ...

**Comment by jema28** [comment]
Hey @egasparini an update on this, we're going with the 5 colours on the Update brand colours page so those will be the things that change (mainly header colours). Let me know if you need any more details?
