### ISSUE TITLE
UC > Server error when approving/rejecting orgs

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#242]
Please see screenshot below of what happens when Maggie tries to approve/reject an organisation on UC Helper Production.

![Image](https://user-images.githubusercontent.com/55511970/213269281-05218124-ecf4-4894-8fc6-fb98274f395f.png)

**Comment by RamyAlshurafa** [comment]
Fixed now
this happened because the fix was not deployed to production
