### ISSUE TITLE
Admin - Organisation approval/rejection

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#25]
**Summary**
From the Organisations overview page yalla-coop/cost-of-living-support#27 admins can mark an org account as approved or rejected. 
If they mark it as approved, they see a pop-up confirming that their action was successful & an automated email is sent to the org.
If they mark it as rejected, they are taken to a separate screen where they provide a reason for rejection, followed by a confirmation pop-up & an automated email is sent to the org. 

Automated approval/rejection emails are covered in task yalla-coop/cost-of-living-support#31  

**Wireframes**
Approved pop-up: https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=4687%3A35672
Rejected: https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=4687%3A35746
Rejected pop-up: https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=4687%3A35673

**Acceptance Criteria**
**Front End**
- [x] Org accepted pop-up:
  - Title: "Organisation approved"
  - Body: "Thanks for reviewing this organisation. They will be notified by email that their profile has now been made public."
  - CTA: "Close"
- [x] Org rejected page:
  - Title: "Confirm rejection" 
  - Body: "Are you sure you wish to reject this organisation? If so, please write a message below that will be emailed to them and click confirm."
  - Explanation input field
  - "Confirm" button
- [x] Org rejected pop-up:
  - Title: "Organisation rejected"
  - Body: "Thanks for reviewing this organisation. They will be notified by email."
  - CTA: "Close"

**UI Criteria**
- [x] Overlay colour is always Neutral / Main (#1A202B) at 80%

**Back End**
- [x] ...
- [x] ...

**Comment by RamyAlshurafa** [comment]
I have made the approval logic on the organizations page (#27) but still need to send the emails which should be covered in #31
