### ISSUE TITLE
Password reset error - client organization/ UC tool

### ISSUE THREAD

**Issue by HYDETS38** [yalla-coop/cost-of-living-support#256]
Priority-2 

One of the organizations subscribed to the UC tool, asked us to change the designated admin person on the account. Following this, the person, cannot change the password. The emails with the links are not being sent to the recipient. 

During repeated manual inputs of the email into the account via the superuser admin, one reset email did manage to get through, however when following the link (on both Edge and Chrome) the page was completely blank, the only item showing being the feedback pop-up message at the bottom.
Unfortunately this could not be replicated again.

Tried to send the password reset message to a hotmail.co.uk email, which produced the same result.

To make sure, have tested sending a direct email (to both accounts) and this was received, within seconds; there is no indication emails are being blocked.  

Uploaded archived saved message.

**Team - do not edit**
[FW Your Universal Credit Support email address was reset.zip](https://github.com/yalla-coop/cost-of-living-support/files/10795599/FW.Your.Universal.Credit.Support.email.address.was.reset.zip)

@thejoefriel

**Comment by Katie-Hyde** [comment]
@cyberteenie can you take a look at this one please as logged in warrantee phase and still not resolved

**Comment by cyberteenie** [comment]
@Katie-Hyde - I will pass this off right away!

**Comment by cyberteenie** [comment]
@Katie-Hyde can you please send me the email addresses via email, to the accounts that you were having this issue with?

**Comment by HYDETS38** [comment]
Please upgrade this to Priority 1. Another agency has reported this issue, on both the UC and the CoL tools. The password reset emails are not coming through at all. They have used Chrome, Edge and Safari,  with the same result. At this point there is a good chance, that should anyone else try to reset their password they will experience the same issue.

**Comment by cyberteenie** [comment]
@HYDETS38 absolutely! I actually spoke with the team earlier today to see where this is at. They have created a fix. It is just being reviewed before merging! I will keep you updated.

**Comment by cyberteenie** [comment]
@HYDETS38 - I believe this change has now been merged in - can you please check that it is working from your end?

**Comment by cyberteenie** [comment]
@HYDETS38 closing this as we never heard back, but feel free to reopen if needed! Thanks!
