### ISSUE TITLE
Creation of monthly report

### ISSUE THREAD

**Issue by cyberteenie** [yalla-coop/cost-of-living-support#258]
From Lucy via email:

So Maggie thought that most of this can come from the google analytics (except the hotjar bit), but thought that it was most sensible to ask you guys to create the reports for us so then we can run them.

 

UC helper

-          Total number for when the translation is used

-          Frequency of translation being used vs not used (i.e. exclusively in English)

 

Cost of living helper 

-          Total users for Cost-of-Living helper

-          Total page views for the Cost-of-Living helper

-          Breakdown by theme for the Cost-of-Living helper (i.e. page views for each theme)

 

For both:

Hotjar user feedback (the smiley face and any comments)  [for UC helper we only need feedback in relation to the translator tool, but I’m not sure if the feedback is that specific?]
 

We need the data from when the UC Helper translator went live and when the CoL Helper went live, so, we’ll need figures for Jan, Feb and march and then going forward to the end of 2023.

**Team - do not edit**
@thejoefriel

**Comment by thejoefriel** [comment]
So the users and pageviews can be done already in analytics. 

The rest can be done in analytics by adding events, which we place in the code. I think that's the best approach. What do you think @RamyAlshurafa ? Can you let Kristina know how we should tackle this from a tech perspective please?

**Comment by RamyAlshurafa** [comment]
Hey @cyberteenie
can you explain this to me please ?
> Breakdown by theme for the Cost-of-Living helper (i.e. page views for each theme)

**Comment by cyberteenie** [comment]
Hi @RamyAlshurafa - I will check in with the Hyde team and see what they say! I will get back to you on this

**Comment by cyberteenie** [comment]
Update from Hyde:

- There is just the default information being generated from the Google Analytics, so they would please like include what has been requested above.
- The totals will be used to generate a report for their funders
- Additionally, they would like that each organisation is set up with its own report
- They may need some training on how to generate the report in Google Analytics, once everything is set up
- Regarding the Hotjar issue, we have clarified that the feedback is not specific to the translator, but is set up for the main portal. That means that Lucy will let the funder know that that feedback is not specific to the part that they funded. They may ask for more specific feedback in the future, but for now, there is no required action on our part regarding the Hotjar issue

@RamyAlshurafa in regards to the breakdown by theme, they mean for each of the tiles (Housing, Bills, Essentials, Debts, Maximising income, etc). I guess these page views will already be visible somewhere in GA, it's just about making them accessible to them.

**Comment by cyberteenie** [comment]
Update after call with Lucy:
- Instead of creating a dashboard, Yalla will focus on cleaning up Google Analytics so that the data that Lucy needs is accessible. We will then provide documentation on how she can access that data within Google Analytics so that she can generate the report manually every month.
- We will need to set up an event tracker for the translation tool stats.

Lucy to double check with Katie about the requirement for each organisation needing their own report.

**Comment by cyberteenie** [comment]
Hi @lucynorgate ! We are currently working on this, but unfortunately I don't think it will be ready for the end of this month. Let me check in with @thejoefriel who is spearheading this and get an eta for you!

**Comment by lucynorgate** [comment]
Hi both - thanks so much for sending this through. I've had a look at the videos and I'll try and carve out some time tomorrow to go through it properly and come back to you if I have any questions, but that looks good. Thank you!

**Comment by thejoefriel** [comment]
No worries at all! And we'll get the language tracking in there asap!

**Comment by lucynorgate** [comment]
Hi - so I had some time to go through this today - all makes sense and I have been able to do the monthly breakdown on page views etc for the GLA. 
Re the translator data - noted that this is live from June only, so will look out for the update on that.
Last thing was the hotjar feedback - mainly for the COL tool as we can't get specific feedback on the translator function for the UC tool. I've logged in to have a look but I may need some help - I haven't used hotjar before so if its possible to do me a quick video to explain how i can get around and understand the data i can collect, that would be a help. second thing was a lot of the time the site says we need to upgrade to access info. Is this a change in what we thought we'd be able to access with our current subscription, or is that additional data I don't need (as I said, I'm new to this so I may just be missing something.

Re closing the isse - I might leave it open until the extra translator reporting is added and also if there is anything more re hotjar. 
Thanks :)

**Comment by thejoefriel** [comment]
No worries @lucynorgate - I've put in an extra video for you. 

As I say in the video, there's no need to upgrade unless you wish to get the further insights. I'd suggest get comfortable with the tool first, see how useful you find it and then you easily upgrade directly in the account :)

**Comment by cyberteenie** [comment]
@lucynorgate - just wanted to check in on this and see if you had any other questions concerning this?

**Comment by lucynorgate** [comment]
Hi - so a couple of questions using the new google analytics:
 - numbers of users - in the old version i could see the total number of users in a calendar mnoth and then how many were new users. I'm only seeing 93 users for June - this s a lot lower than the previous months total users and new users, but I'm not sure if there is a different way to find that data?
 - I'm not quite sure what the Event Count is (one the first page I've put in the dates for June and can see that there are 93 new users, and the Event Count is 669). At first I wondered if that was the same as page views, but now am thinking its different. 
 - I think I know how to find page view - click on reports, Engagement, Pages and screens. I've put in the dates for June and it appear to show me a total of 337 page views, but then those are broken down in quite a detailed way, via each version of the tool , so it might be that Section 3 (paying for essentials) has been looked at 5 times but i have to scroll through and see if there is views for the Hyde housing version, the Adur & Worthing version, etc and its quite open to human error to get the right numer of views (I've just done it and made a mistake somewhere). Do you know if I can do this more by the different sections across all the versions of the tool, or is this the only way to view it?
 - if that is the right way to do page views, then its quite different to the breakdown I was getting before i think, but also I can't load the old analytics pages, nothing happens when i click on those links, so i can't go back to check that data and see if i can be more consistent across the reporting period.
 - In the previous version of analytics it gave us number of sessions, which I had reported to the GLA, but i can't see how to find this data now.
 - Also, are you able to show me how to access the data about the translator tool?
Thanks, Lucy

**Comment by thejoefriel** [comment]
Hey @lucynorgate in good news we are now tracking successfully language tracking within the app. I've created a new video for you. We are just making a final tweak to work around Google's quirks of not displaying labels in the reports. This will get sorted this week. But overall the tracking is now in there. 

Thanks!

**Comment by lucynorgate** [comment]
Thats great @thejoefriel - thanks. So in terms of being able to report on it, is that available only from now, or can I access reports for June? Cheers

**Comment by lucynorgate** [comment]
Hi again @thejoefriel - to answer your question above "When you say the old analytics pages what do you mean sorry? You should still be able to see the old analytics, it's just stopped collecting data. Let me know if you're having issues accessing this and I'll look into it for you."
So when trying to look at data for before google moved to the new version of analytics, when I tried to load the old version pages (the ones without the GA4 next to them) I was getting no data, it just looked like everything was at 0. But, the link you adde din your answer above, did give me data for those old version analytics, so I'm not sure what happened there.
My other question on when I go into the list of which analytics page I want to look at, is: there are 2 links to open the COL Helper GA4 - one deafaults to last 7 days and one to last 30 days. i'm guessing theres not much differnece between them, but can you advise if theres one i should be using?

![image](https://github.com/yalla-coop/cost-of-living-support/assets/130667915/3933de34-e8e0-4856-8c83-b5cca15d3d47)

Thanks

**Comment by thejoefriel** [comment]
Hey @lucynorgate we've managed to make it easier for you to see languages now. I've just updated the notion doc with another video. 
For UC Helper, we deployed that over the weekend so should start showing properly now.

**Comment by thejoefriel** [comment]
Yeah the one to use @lucynorgate is "COL helper-GA4" - the other one is a redundant one that Google created but won't let me remove right now

**Comment by cyberteenie** [comment]
Hi @lucynorgate - just wanted to check in to see if we are now good to close this issue?

**Comment by lucynorgate** [comment]
Hi - yes i think so

> Hi @lucynorgate - just wanted to check in to see if we are now good to close this issue?

**Comment by cyberteenie** [comment]
Great thanks!
