### ISSUE TITLE
Admin - Organisation details

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#26]
**Summary**
On this page an admin can view the details of an Organisation.
Org details should also be editable by super admins, so if someone leaves the organisation, they can change the email address etc. Changing the email address should trigger a sign up email to the user with a link to reset their password. The email template sent in this scenario is covered in #107 

**_> Editable input fields & trigger sign up email when email address is changed are also needed on UC Helper._**

**Note**
- This is to be updated on UC and CoL helpers
- It is basically just the Edit Account page that the Organisation sees https://github.com/yalla-coop/cost-of-living-support/issues/38 so ideally just use that existing page 

**Wireframes**
Desktop: https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=4687%3A35728

**Acceptance Criteria**
**Front End**
- [x] "Organisation details" title
- [x] Editable input fields: 
  - First name
  - Last name
  - Email address 
    - Changing the email address should trigger a sign up email to the user with a link to reset their password. 
  - Back up email address   
  - Organisation
  - Type of organisation
  - Your unique link
  - Contact Details
  - Type of contact
  - Phone Number
  - Availability
  - Description
- [x] Button to "Save changes"

**UI Criteria**
- Nothing to add

**Back End**
- [x] ...
- [x] ...

**Comment by RamyAlshurafa** [comment]
Hey @egasparini 
can you open an issue for @Israa91 to create a new template in Sendgrid, (i will add the functionality in my PR, but she should update the template id when she creates it)
Thanks

**Comment by egasparini** [comment]
@RamyAlshurafa is the template about the automated email sent when a super admin changes an org's email address?

**Comment by RamyAlshurafa** [comment]
> @RamyAlshurafa is the template about the automated email sent when a super admin changes an org's email address?

yeah exactly
