### ISSUE TITLE
Set up Better Uptime for https://col-helper.co.uk/

### ISSUE THREAD

**Issue by cyberteenie** [yalla-coop/cost-of-living-support#264]
Better Uptime has been already set up for uc-helper.co.uk, but we still need it for https://col-helper.co.uk/

**Team - do not edit**
@thejoefriel
@dupreesi 
@Ibrahim-Jarada

**Comment by cyberteenie** [comment]
Fadi can support in regards to process.

**Comment by Ibrahim-Jarada** [comment]
@cyberteenie I need Better Uptime credentials which used for uc-helper.co.uk

**Comment by Ibrahim-Jarada** [comment]
Hey @cyberteenie  you can close this as completed

![image](https://user-images.githubusercontent.com/48867411/235888013-ce6fe077-c9e9-4739-b1f4-9998175b8d09.png)

![image](https://user-images.githubusercontent.com/48867411/235887474-38500d65-de83-4b4b-923a-f16e69d42d8d.png)

**Comment by cyberteenie** [comment]
@Ibrahim-Jarada thank you!
