### ISSUE TITLE
Test if Google Analytics Events are triggered

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/cost-of-living-support#270]
### Please select the priority level by adding one of the following labels to this issue?

Priority-2 (High e.g. Core functionality is not working)

### Describe the bug and the expected behaviour.

We updated to GA-4 and apparently the event triggers aren't working. Please check it. E.g. this event: 
https://github.com/yalla-coop/cost-of-living-support/pull/266/files

Please test the same on the other repo.

**Comment by thejoefriel** [comment]
Hey @RamyAlshurafa unfortunately GA4 still doesn't allow you to view labels in the report view. I've tried creating custom reports etc but still doesn't work. Can you revert back to our original plan for the event name to be "change_language_${lng}" please?

**Comment by cyberteenie** [comment]
Confirmed as working by @thejoefriel
