### ISSUE TITLE
Cookiebot not working for CoL tool

### ISSUE THREAD

**Issue by RamyAlshurafa** [yalla-coop/cost-of-living-support#272]
### Please select the priority level by adding one of the following labels to this issue?

Priority-2

### Describe the bug and the expected behaviour.

In console warning section you can see this message
Error: The domain COL-HELPER.CO.UK is not authorized to show the cookie banner for domain group ID c3a532f5-4d84-4594-a389-41aa105c1da2. Please add it to the domain group in the Cookiebot Manager to authorize the domain.

**Comment by RamyAlshurafa** [comment]
Hey @cyberteenie 
this is done now, i also fixed it for the UC helper as well

**Comment by cyberteenie** [comment]
Thanks Ramy
