### ISSUE TITLE
Admin - Dashboard

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#28]
**Summary**
The admin dashboard is the place where admin go to:
* review new org accounts
* review new submitted sections
* edit content
* make changes
* edit details
* customise

**Note**
Use the existing dashboard in the codebase and edit 

**Wireframes**
Desktop: https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=5367%3A25910

**Acceptance Criteria**
**Front End**
- [x] Left side nav includes:
  - [x] Hyde logo
  - [x] Home
  - [x] ~~Edit content~~ Add/update content -> this should be hidden until we build the "Add/update content" functionality
  - [x] Organisations
  - [x] Changes
  - [x] Edit details
  - [x] ~~Customise~~ Add/update brand colours 
  - [x] Log out 
- [x] When there are organisation accounts to review, the admin sees a pop up on their dashboard prompting them to review them. 
  - [x] Title is "Organisation to approve" 
  - [x] Pop up description "You have organisations awaiting for approval. Please click to review them below."
  - [x] "Review" button > takes the user to the Organisations page

**UI Criteria**
- [x] Need to confirm with @thejoefriel that the navbar is still correct?
- [x] Check spacing between Analytics header and analytics block
- [x] 64px between columns

**Back End**
- [x]  add a new column in the DB to store the org's status
- [x]  for UC helper create migration files
- [x]  send the status to the front end

**Comment by egasparini** [comment]
@fadeomar I just updated the Front End AC of the left side menu based on what's on discord.

**Comment by fadeomar** [comment]
> @fadeomar I just updated the Front End AC of the left side menu based on what's on discord.

thanks @egasparini I'm going to update the code in the PR to match the updates
