### ISSUE TITLE
Account registration information

### ISSUE THREAD

**Issue by HYDETS38** [yalla-coop/cost-of-living-support#280]
### Is your feature / client request related to a problem? Please describe.

On registration, agencies are requested to provide two email addresses. Following past conversations, it was decided as a matter of policy for these to be organization registered only, so no personal ones i.e., Gmail, Hotmail, Outlook etc.
Unfortunately as the applicants don't have this instruction, they will list personal emails. The issue has to be rectified by messaging the applicants individually.

### Describe the solution you'd like

Text note (perhaps, in the page body) instructing the applicants on the requirement of organization based only email addresses.

### Describe alternatives you've considered

N/A

### Screenshots or a link to a Loom Recording

N/A

**Comment by cyberteenie** [comment]
Thanks for adding this. Can you please provide the exact copy you would like added? Thanks!

**Comment by cyberteenie** [comment]
We will add this copy as requested by email:

**When setting up an account please use a company email address we are unable to accept personal email addresses. This should be with the organisation you are registering.**

**Comment by RamyAlshurafa** [comment]
this has been done, and deployed, @HYDETS38 can you check, please?
when the user starts filling the backup email, we show them the tip.

**Comment by cyberteenie** [comment]
@HYDETS38 @Katie-Hyde just wanted to flag that this is ready for review as well.

**Comment by Katie-Hyde** [comment]
Hi

Can you screen shot changes and I'll sign off. I can't see as it just takes me to my super admin or Hyde's version

Katie

Katie Ford
Programme Manager Advice & Advocacy Service
The Hyde Group

T: 01243 816943
M: 07918 768587
E: ***@***.******@***.***>

The Hyde Group * Martlet House * Southern Gate  * Chichester * PO19 8SG
www.hyde-housing.co.uk<http://www.hyde-housing.co.uk/>

Follow us: Twitter<https://twitter.com/HydeHousing> * Facebook<http://www.facebook.com/HydeGroup> * LinkedIn<https://www.linkedin.com/company/the-hyde-group> * YouTube<https://www.youtube.com/channel/UCQPM3E8plfyi9EWgHrbiyHQ> * Instagram<https://www.instagram.com/thehydegroup/>

UC helper<https://www.uc-helper.co.uk/hyde-housing> - a step-by-step guide to applying for Universal Credit
Cost of living helper<https://col-helper.co.uk/hyde-housing> - help and support at your fingertips

**Comment by RamyAlshurafa** [comment]
@Katie-Hyde 
![image](https://github.com/yalla-coop/cost-of-living-support/assets/34629478/6f3b9b3e-fb43-4bdd-bb68-5b3dc275ccbc)

**Comment by Katie-Hyde** [comment]
brilliant thank you, happy with tip
