### ISSUE TITLE
Logo displays too small

### ISSUE THREAD

**Issue by HYDETS38** [yalla-coop/cost-of-living-support#281]
### Please select the priority level by adding one of the following labels to this issue?

Priority-2 (High e.g. Core functionality is not working)

### Describe the bug and the expected behaviour.

Issue reported by external organization

From: Bailey, Stuart <Stuart.Bailey@southernwater.co.uk> 
Sent: Tuesday, July 18, 2023 1:50 PM
To: Hyde <no-reply@col-helper.co.uk>
Cc: Tomi Stan <tomi.stan@hyde-housing.co.uk>
Subject: RE: Cost of Living profile approved

This message originated from outside your organization.
Good afternoon,
Further to the below, I have been informed by our Brand Support that the Southern Water logo has not been updated on the below link?
Can you please help?

Many thanks.
Stuart Bailey
Vulnerability Liaison Officer (Hants & I.O.W)
T. 0800 027 0800
M. 07775 407017
southernwater.co.uk

Logo displays very small.

### Steps To Reproduce

Access via https://col-helper.co.uk/southern-water

### Screenshots or a link to a Loom Recording

https://col-helper.co.uk/southern-water

### What browsers are you seeing the problem on?

Other

### Anything else?

Any.

**Comment by cyberteenie** [comment]
Hi @HYDETS38 ! We can certainly fix this for you!
One thing I will mention is that we would probably classify this as a priority 4 bug, as it is technically working and not impeding functionality, just not displaying properly. No worries, but just thought I would mention it for the future!

**Comment by cyberteenie** [comment]
@RamyAlshurafa - question for you.
@Katie-Hyde has inquired whether or not this has been applied for all organisations or just for Southern Water? Ideally they want it applied across all organisations.

**Comment by cyberteenie** [comment]
@Katie-Hyde - this has been applied across all the organisations!
