### ISSUE TITLE
Adding an icon to a new tile

### ISSUE THREAD

**Issue by cyberteenie** [yalla-coop/cost-of-living-support#283]
### Please select the priority level by adding one of the following labels to this issue?

Priority-3 (Normal e.g. Functionality is not working for a subset of users)

### Describe the bug and the expected behaviour.

From Katie via email:

we allow organisations to add a new tile of there choice there are options for title and content but when displayed on the main page it should come up with the title and an icon on the tile. There is no option to add an icon on the tile, e.g are tiles with a house, calculator, bill, shopping basket, money bag.

**Comment by cyberteenie** [comment]
@RamyAlshurafa - is this ready for client review?

**Comment by cyberteenie** [comment]
Hi @Katie-Hyde - this is ready for testing as well :)

**Comment by cyberteenie** [comment]
@Katie-Hyde - just wanted to check to see if we are good to close this issue?

**Comment by Katie-Hyde** [comment]
Yes great thanks

Katie Ford
Programme Manager Advice & Advocacy Service
The Hyde Group

T: 01243 816943
M: 07918 768587
E: ***@***.******@***.***>

The Hyde Group * Martlet House * Southern Gate  * Chichester * PO19 8SG
www.hyde-housing.co.uk<http://www.hyde-housing.co.uk/>

Follow us: Twitter<https://twitter.com/HydeHousing> * Facebook<http://www.facebook.com/HydeGroup> * LinkedIn<https://www.linkedin.com/company/the-hyde-group> * YouTube<https://www.youtube.com/channel/UCQPM3E8plfyi9EWgHrbiyHQ> * Instagram<https://www.instagram.com/thehydegroup/>

UC helper<https://www.uc-helper.co.uk/hyde-housing> - a step-by-step guide to applying for Universal Credit
Cost of living helper<https://col-helper.co.uk/hyde-housing> - help and support at your fingertips

**Comment by cyberteenie** [comment]
Great, thank you!
