### ISSUE TITLE
Admin - Review new section

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#29]
**Summary**
This is the place where admins go to review new sections submitted by organisations. Here they can approve or reject a section + provide a comment.

**Wireframes**
https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=5592%3A24739 
https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=5592%3A24912

**Acceptance Criteria**
**Front End**
- [x] Add a new item in the left nav bar called "Content review" - this should be between Organisations and Changes.
- [x] Clicking on "Content review" users see a list of content that needs to be reviewed. The list shows:
   - Name > this links to the Org detail page
   - Email
   - View content > this shows the section name and links to the section details page
- [x] Clicking on the section name, we take the admin to a new page where they see the details of the section. This page looks exactly like the "Add section: page yalla-coop/cost-of-living-support#35 and has some actions at the bottom:
   - [x] Button: Approve section
   - [x] Button: Preview in a new tab > opens the preview in a new tab
   - [x] Text: Reject section
- [x] When admin clicks on "Approve section" they see a [confirmation modal](https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=5624%3A25254) 
- [x] When admin clicks on "Reject section" they are taken to a new page where they need to provide a reason for rejection. 
   - [x] The page looks just like the [account rejection page](https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=4687%3A35746) with adjusted copy: "Are you sure you wish to reject this section? If so, please write your feedback below that will be emailed to them and click confirm." **(COPY TBD)**
   - [x] When they click on "Confirm" they see a [confirmation modal](https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=5637%3A25439)

**UI Criteria**
- [x] Need to add review new section wireframes once there's confirmation on placement
- [x] Again, the arrows follow the pattern in the screenshot below and then repeat  

**Back End**
- [x] ...
- [x] ...

**Comment by jema28** [comment]
Just to confirm all the designs are done for this @egasparini but let me know if there's anything else you need?

**Comment by egasparini** [comment]
It's all good @jema28! I already updated the task based on your designs. Thank you for checking in :)
