### ISSUE TITLE
Org - Add/update brand colours

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#33]
**Summary**
On this page Organisations can customise the colour scheme of their CoL Helper & upload their logo.

**Wireframes**
Desktop: https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=4617%3A19117

**Acceptance Criteria**
**Front End**
- [x] "Add/update brand colours" title
- [x] Page description
- [x] Logo section with upload functionality 
- [x] Colour section displaying current selected colours, where users can pick their preferred colours:
  - [x] Main background colour 
  - [x] Main text color
  - [x] Secondary background colour
  - [x] Secondary text color
  - [x] Tertiary background colour
  - [x] Tertiary text color
  - [x] Quaternary background colour
  - [x] Quaternary text color
  - [x] Quinary background colour
  - [x] Quinary text color
- [x] When a user clicks on a colour they see a colour picker. They can choose a colour from a gradient, specify the Hex value or RGBA values. It looks like this: https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=5194%3A24717
- [x] Below the colours section there's a tooltip reminding users about accessibility, with a link to more information: https://webaim.org/resources/contrastchecker/
- [x] Tickbox to use gradients vs solid colours **_> also needed on UC Helper_**
- [x] Button to "Save changes"

**UI Criteria**

**Background colours**
1. Main background colour -> Secondary - Main
2. Secondary background colour -> Tertiary - Main
3. Tertiary background colour -> Neutral - Mid
4. Quartenary background colour -> Neutral - Light
5. Quinary background colour -> Neutral - Main

**Foreground colours**
1. Main and quinary text colour -> White
2. Secondary, tertiary, quarternary -> Neutral - Main

**Back End**
- [x] ...
- [x] ...

**Comment by fadeomar** [comment]
hey @jema28  here is the link from the current app https://webaim.org/resources/contrastchecker/

**Comment by fadeomar** [comment]
Background colours
1. Main background colour -> Secondary - Main
2. Secondary background colour -> Tertiary - Main
3. Tertiary background colour -> Neutral - Mid
4. Quartenary background colour -> Neutral - Light
5. Quinary background colour -> Neutral - Main

Foreground colours
1. Main and quinary text colour -> White
2. Secondary, tertiary, quarternary -> Neutral - Main

**Comment by thejoefriel** [comment]
- Find anywhere that uses any of the primary, secondary, tertiary etc colours as the background colour AND there if there is any text, give it the linked text color (so if a background colour is primary then you need to make sure the color for the text is primaryText)

- Find anywhere that uses neutralMain as a background and if there is text on top it needs to be the quinaryText color

- Find anywhere that uses neutralMid as a background colour and if there is text on top it needs to be the tertiaryText colour

- Find anywhere that uses neutralLight as a background colour and if there is text on top it needs to be the quartenaryText colour

**Comment by egasparini** [comment]
@fadeomar - as discussed, we need to revert these changes both for UC & CoL. 

Moreover we want to make these changes on CoL (only): 
- [ ] Below "Colours" add copy: "The default main header is a gradient background. If you would like to change it to your main brand colour you can do that below."
- [ ] Add colour picker for `Main header background colour`. This should have a separate label. Changing this value changes the background colour of the header. The default is Hyde's gradient image and when that's being used the colour picker should look empty.
![image](https://user-images.githubusercontent.com/55511970/205040405-5d113755-9c3a-457d-a3e9-9dfe154f2fe3.png)

- [ ] Add copy: "To change the main section cards on the landing page and each section header, please select your brand colours below."
- [ ] Create separate labels for each Section / Header. We have 5 sections, and each one should have a customisable background colour and text colour. The background colour also changes the colour of the little arrow icon on the landing page.
![Image](https://user-images.githubusercontent.com/55511970/205031759-bb7e812e-d047-4139-9cd8-7ed9e1779b6b.png) ![Image](https://user-images.githubusercontent.com/55511970/205031455-dd616b88-b204-4392-862a-ddcaffd14274.png)
- [ ] Section colours should be renamed from -> to:  
   - [ ] Main background colour -> Section 1 background colour
   - [ ] Main text color -> Section 1 text colour
   - [ ] Secondary background colour -> Section 2 background colour
   - [ ] Secondary text color -> Section 2 text colour
   - [ ] Tertiary background colour -> Section 3 background colour
   - [ ] Tertiary text color -> Section 3 text colour
   - [ ] Quaternary background colour -> Section 4 background colour
   - [ ] Quaternary text color -> Section 4 text colour
   - [ ] Quinary background colour -> Section 5 background colour
   - [ ] Quinary text color  -> Section 5 text colour
- [ ] If organisations create new sections, the colours repeat; so the 6th section will use the Main colour background & text, and the 7th section will use the Secondary background colour & text.
- [ ] Org logo: we should display the one uploaded by the organisation if they uploaded one.

**Comment by remaininlight** [comment]
Colours reverted to using 'Main colour' and 'Secondary colour' in UC. Card colours and backgrounds in CoL
