### ISSUE TITLE
Unable to approve Teign Housing as it just states server error

### ISSUE THREAD

**Issue by cyberteenie** [yalla-coop/cost-of-living-support#348]
### Please select the priority level by adding one of the following labels to this issue?

Priority-2 (High e.g. Core functionality is not working)

### Describe the bug and the expected behaviour.

Reported by Katie via email.
I have also tested it with logins email

<img width="946" alt="Screenshot 2024-08-07 at 13 37 26" src="https://github.com/user-attachments/assets/80df4119-959d-4aa9-9ffa-9226a43f3f96">

**Comment by RamyAlshurafa** [comment]
@cyberteenie 
fixed and deployed
