### ISSUE TITLE
Org - Add/update content - Add section

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#35]
**Summary**
On this page Orgs can add a new section, with its related Actions and Helpful Resources.
When they submit a new section it is sent to admin for approval. That part of the flow is tackled on yalla-coop/cost-of-living-support#32 , yalla-coop/cost-of-living-support#30 and yalla-coop/cost-of-living-support#29

**Wireframes**
Desktop: 
* one action: https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=5104%3A27454
* multiple actions: https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=5106%3A29172
* publish content: https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=4658%3A17688
* page preview: https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=5191%3A27220
* card / action: https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=5104%3A28131

**Acceptance Criteria**
**Front End**
1. "Add/update content" page
- [x] "Add new section" button (only visible if the org has less than 2 custom sections) 
- [x] "Under review" section (only visible if the org submitted a new section for review)

2. "Add section page"
- [x] "Add section" title
- [x] Copy to describe what can be done on this page 
- [x] Input field: Section title
- [x] Action 1 
  - [x] Actions are encased in a box with a red border  
  - [x] Input field: Title
  - [x] "See more" dropdown > when clicked the box expands and you see some extra fields:
    - [x] "Description"
    - [x] "Tips" (optional) with a X to delete
    - [x] Button to "Add another tip"
  - [x] Below the box is a button to remove that Action
- [x] Helpful Resources section
  - [x] Resource link with description & input field
  - [x] Resource label with description & input field
  - [x] Button to "Add another resource" -> limit to 3 resources, then hide "add" button 
  - [x] Clicking on that button shows one more Resource link & Resource label with their respective input field
- [x] Line divider, below which there's a button to "Add another action" -> limit to 5 actions, then hide "add" button
- [x] Below are two buttons: "Publish" and "Preview in a new tab" 
  - [x] "Publish" takes the user to a Thank you page with two CTAs:
    - "Edit Content" takes them back to "Add/update content"
    - "Back to dashboard" takes them back to the dashboard home page
  - [x] "Preview in a new tab" opens the preview in a new tab of the content they entered > also needed for UC Helper, see dedicated task yalla-coop/cost-of-living-support#14 

**UI Criteria**
- Nothing to add

**Back End**
- [ ] ...
- [ ] ...

**Comment by thejoefriel** [comment]
Hey @maggiehoughton to check, if an organisation edits their custom section after it's been approved, it would be subject to approval again right?

**Comment by RamyAlshurafa** [comment]
also @maggiehoughton 
if you go with the need to be re-approved, should their page disappear until they get approved again, or we should show the old content until they get approved?

**Comment by thejoefriel** [comment]
Thanks @maggiehoughton ok so to be clear you're saying re-approving content updates is a bonus feature rather than essential right now?

**Comment by maggiehoughton** [comment]
Yep, it's about minimising risk but we're doing most of that when we check credentials on sign up.

**Comment by thejoefriel** [comment]
OK great, so right now we will ensure you can approve when a new content section is created, but once approved then they can keep making changes if they want. If we have time we will then discuss if we want to set up re-approval 

Sounds good!

**Comment by egasparini** [comment]
@maggiehoughton about your point:
 
> Can we add in a disclaimer sentence again for the approval confirmation email? I think I already wrote this out somewhere else, but something to the effect of "Hyde does not verify or check any content published by other organisations on the CoL Helper. Please make sure you are happy that the information you publish is correct."

This is captured here: #32
