### ISSUE TITLE
Org - Edit contact details

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#38]
**Summary**
In this page, Organisations can update the contact details they provided when they created their account, their adviser contact line and their unique link. 

**Wireframes**
Desktop: https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=4617%3A19083 

**Please note: This issue also includes updating the UC Helper to match this new flow.** 

**Acceptance Criteria**
**Front End**
- [x] Details that orgs can edit are:
  - First name
  - Last name 
  - Email address
  - Back up email address
  - Organisation
  - Type of organisation 
  - Unique link with max slug length = 50 characters
- [x] "Save changes" button

**UI Criteria**
- Nothing to add

**Back End**
- [x] Use existing API endpoints, and update queries

**Comment by thejoefriel** [comment]
I think basic validation so:
- Required fields
- Email format
- String type

That's about it

**Comment by remaininlight** [comment]
@thejoefriel Do we have a list of types of organisation for the 'Type of organisation' dropdown please?

**Comment by thejoefriel** [comment]
No @maggiehoughton would be best for this - Maggie you able to send list of organisation types please?

**Comment by maggiehoughton** [comment]
Local Authority
Housing Association
Credit Union
Local/regional charity or community organisation
National charity
Other

**Comment by thejoefriel** [comment]
Thanks @maggiehoughton - all yours @remaininlight

**Comment by remaininlight** [comment]
Thanks @maggiehoughton @thejoefriel!

**Comment by remaininlight** [comment]
@maggiehoughton I've found a list of organisation types which is used on signup (below). Is this the same field? Would you like me to replace the list here with the one you've provided or should I use the list already used on signup?

https://github.com/yalla-coop/cost-of-living-support/blob/develop/client/src/constants/data-types.js#L37
```
INFORMAL_OR_CONSTITUTED_COMMUNITY_GROUP_LITTLE_OR_NO_ANNUAL_INCOME:
    'Informal or constituted community group [little or no annual income]',
  MICRO_CHARITY_VOLUNTARY_ORGANISATION__LESS_THAN_10000_ANNUAL_INCOME:
    'Micro Charity / Voluntary Organisation [Less than £10,000 annual income]',
  SMALL_CHARITY_VOLUNTARY_ORGANISATION_10000_TO_100000_ANNUAL_INCOME:
    'Small Charity / Voluntary Organisation [£10,000 to £100,000 annual income]',
  MEDIUM_SIZE_CHARITY_VOLUNTARY_ORGANISATION_100000_TO_1M_ANNUAL_INCOME:
    'Medium Size Charity / Voluntary Organisation [£100,000 to £1m annual income]',
  LARGE_CHARITY_VOLUNTARY_ORGANISATION_1M_TO_10M_ANNUAL_INCOME:
    'Large Charity / Voluntary Organisation [£1m to 10m annual income]',
  MAJOR_CHARITY_VOLUNTARY_ORGANISATION_10M_ANNUAL_INCOME:
    'Major Charity / Voluntary Organisation [£10m+ annual income]',
  LOCAL_GOVERNMENT: 'Local Government',
  NATIONAL_GOVERNMENT: 'National Government',
  NHS_CCG: 'NHS / CCG',
  COMMUNITY_INTEREST_COMPANY: 'Community Interest Company',
  SOCIAL_ENTERPRISE: 'Social Enterprise',
  SCHOOL: 'School',
  FAITH_ORGANISATION: 'Faith Organisation',
```

**Comment by remaininlight** [comment]
PR is here:
https://github.com/yalla-coop/cost-of-living-support/pull/102

**Comment by fadeomar** [comment]
hey @remaininlight, I've reviewed your PR, nice work, I've only one note about the tip content, it says " Please note that changing your unique link will mean we need to review your profile again", and we should consider this point in this when work on changing the organisation statuses I think @RamyAlshurafa will work on that next, @RamyAlshurafa can take in your consider this point when you work on organisations statues, please?
