### ISSUE TITLE
Org - Account creation

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#44]
**Summary**
We want Organisations to be able to create an account and configure their own CoL Helper.
The Sign up process is composed of the following steps: 
1. Landing page
2. Sign up
3. Success

**Please note: This issue also includes updating the UC Helper to match this new flow. There are some slight variations on the copy so please double check wireframes**

**Wireframes**
Desktop: 
1. Landing page https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=4617%3A18888 
2. Sign up (1) https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=4617%3A18898 
Sign up (2) https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=4617%3A18908 
3. Success https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=4617%3A19043

UC Helper variation:
https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=5838%3A23607

**Acceptance Criteria**
**Front End**

  0. General
- [x] The page is horizontally split in two. The left side has a black to blue gradient. The right side is white and displays the needed content.   
1. Landing page
- [x] Hyde logo
- [x] Welcome title + extra copy
- [x] Link to "view demo video" -> opens the video in a new tab
- [x] "Sign up" button takes the user to the next step
2. Sign up
- [x] Hyde logo
- [x] Sign up title & Sign up fields: @jema28 are all fields mandatory? Should we do validation on submit?
  - First name
  - Last name
  - Email address
  - Back up email address
  - Password
    - Question mark icon, if clicked it shows a tooltip with password requirements
    - if password requirements aren't met we show an error message -> @jema28 do we have a mockup of how this should look like? how specific do we want to be? 
  - Organisation
  - Type of organisation (Dropdown) -> @jema28 do you know what the options are?
  - Checkbox to agree to T&Cs + Privacy Policy **_> also needed on UC Helper_**
  - "Sign up" button completed the process and takes the user to the next page
3. Success
- [x] Hyde logo
- [x] Success title & copy
- [x] button to "Go to dashboard"
- [x] create an API call to sign new orgs up

**UI Criteria**
- [x] Layout around content: 80px top margin, 120px left margin. 120px bottom margin if that screen has content that scrolls. If not, the page width should just be the full page height. 
![CleanShot 2022-10-27 at 05 44 22](https://user-images.githubusercontent.com/25960351/198193939-c5ec5ff6-97d4-4733-b25c-162bb6012201.gif)

_Note: if you see anything different, please ignore and follow the rules above_ 
- [x] For inputs, placeholders should always be Neutral / Dark, filled in content should be Neutral / Main
- [x] For body text, colour should always be Neutral / Dark apart from links which should be Neutral / Main 

**Back End**
- [x] Create an API endpoint (use the one is already there) to signup

**Comment by thejoefriel** [comment]
Yeah it'll be a loom link. I'll be recording it once we've created the app as it's a video demo'ing the app so for now use the same one that's already on UC helper as a placeholder. Thanks!
