### ISSUE TITLE
Language Selector

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#53]
**Summary**
Not everyone visiting the CoL & UC websites will be English speakers. We want to make sure that people can receive the support they need independently from the language they speak. 
Therefore, above the website header we want to have a language switcher that allows visitors to view the website in their language of choice.

_Note: The language selector should be built both for CoL & UC._

**Wireframes**
Desktop: 
- Top bar nav: https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=5099%3A26651
- Language selector: https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=4805%3A17646
 
Mobile: 
- Top bar nav: https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=4813%3A17506
- Language selector: https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=4746%3A28251
- Right to left formatting: https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=4813%3A17316

**Acceptance Criteria**
**Front End**
- [x] Website has an always visible top bar with the language switcher on the top right.
- [x] Language switcher is composed of language flag and language name. On mobile the language name is displayed as a 2 letter country code, e.g. EN for English
- [x] Clicking on the language switcher opens a full screen menu with the language selector
- [x] On the left side of the top bar there's an arrow pointing back that closes the full screen menu    
- [x] Language selector has a search box on top, below which it displays the first 12 languages in alphabetical order with their corresponding flag. Each language is written in its own language, e.g. español, nederlands, italiano, deutsch, etc.
- [x] Visitors can use the search box to find their language
- [x] When a user selects a language, the language selector closes and the website is displayed in the language they selected. Right to left languages are displayed with right to left formatting
- [x] When the user leaves and comes back to the website at a later stage, we remember their language selection 
- [x] Detect browser language
- [x] Use i18next and i18next-react to retrieve and present JSON from database

**UI Criteria**
- [ ] All the languages can be found here. The design is outdated now but shows a full list of languages: https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=5339%3A24649
- [ ] Question: where are we getting the right to left data from. Is this something you looked into @cemalokten?
- [ ] Question: will the font work for all right to left languages? 
- [ ] All the flags can be found here: https://www.figma.com/file/y3YS7RNBQAlqJHve7VfF9A/Shipfaster-UI---v2.3-(Live)?node-id=54%3A1236
- [x] When there isn't a flag there is a blank space e.g. Aymara
- [x] To confirm with @cemalokten: While searching the selection will decrease e.g. Af for Afrikaans
- [x] The search icon isn't clickable, it's just for decoration 

**Back End**
- [x] Store language selected in cookies/localstorage for **xxx amount of time**
- [ ] Google translate integration?
- [x] Store static content translations in database JSON

**Comment by cemalokten** [comment]
@jema28 Hey! I've noticed that the arrows on the translation bar are not symmetrical:

![image](https://user-images.githubusercontent.com/60609268/200828961-ac7b0862-e0e4-4d3f-9abc-8b38fa10cf50.png)

Is this intended?

**Comment by jema28** [comment]
It's an icon from Feather icons so all good @cemalokten

**Comment by cemalokten** [comment]
### Additional tasks:
Backend
- [ ] Add i18n tables for other content that requires translation
- [ ] Add logic to fetch additional content translation
- [ ] Add logic to dynamically translate missing languages

Frontend
- [ ] Add remaining flags - suggest we start with 12 most popular languages and then add additional when it has been tested
- [ ] Add context to return value that can be used in styles to flip reading direction

**Comment by RamyAlshurafa** [comment]
Im working on 
- [ ]  Go through site and replace common text with translated
- [ ] translate sections in the landing page
- [ ] translate select sub-section page
