### ISSUE TITLE
CoL Landing page

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#54]
**Summary** 
The Cost of Living Helper landing page is the starting point for visitors in need of help to find the support and pointers they need to take action.

The landing page is composed of a top bar with accessibility toggle and language switcher, a header, the main content of the page that directs the user to detail pages, and two calls to action at the bottom.  

**Notes**
As with all the pages, this will be working from the landing page we have already created for UC helper and then editing it

**Wireframes**
Desktop: https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=5099%3A26554
Mobile: https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=4665%3A17296

**Acceptance Criteria**
**Front End**
- [x] Page has header with Hyde logo and title "Cost of Living Helper" 
- [x] Below the header is some copy as in the wireframes
- [x] This section includes 5 buttons that will take visitors to detail pages of each topic:
   - [x] Paying for housing
   - [x] Paying for my bills
   - [x] Paying for essentials
   - [x] Dealing with debts
   - [x] How to maximise my income
   - [x] NOTE: it can be up to 7 buttons, as admins can add 2 extra ones
- [x] Below there is another section "Need help with budgeting" with a link to "Read more" pointing to a separate page
- [ ] At the bottom there is a final section "Feeling stressed or overwhelmed" followed by a button with CTA to "See advice" and a prompt to talk to someone.
- [x] Create API call to fetch sections

**UI Criteria**
- [ ] The accessibility bar should be fixed as you scroll (this applies for every page)
- [x] On the landing page there isn't a back button in the accessibility bar. On every other page there is 
- [x] There is 37.5px padding on left and right in mobile with the content then filling the space if the screen is bigger than 375px
- [x] The background of the Budgeting section goes full width in mobile but 1200px max width in desktop (see desktop link above)

**Back End**
- [x] Create sections API endpoint 
- [x] Create query to get sections
- [x] Create initial section content in database

**Comment by RamyAlshurafa** [comment]
Hey @egasparini @jema28 @thejoefriel 
Where the "See advice" button should go?

**Comment by RamyAlshurafa** [comment]
for 
> The accessibility bar should be fixed as you scroll (this applies for every page)

this is created in #77

**Comment by jema28** [comment]
> Hey @egasparini @jema28 @thejoefriel Where the "See advice" button should go?

Hey @RamyAlshurafa that should go to the Mental Health page

**Comment by RamyAlshurafa** [comment]
ok thanks @jema28
