### ISSUE TITLE
Set up Hotjar

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#55]
Both for UC & CoL
Should use a free tier account

**Comment by Israa91** [comment]
Hi @maggiehoughton ,I used this email [CoLdigital@hyde-housing.co.uk](mailto:CoLdigital@hyde-housing.co.uk) to create account on hotjar ,they send code for this email ,can you please send me this email to continue ? thanks.

**Comment by maggiehoughton** [comment]
Welcome! 

To get started, please enter this code to confirm it’s you. 
089150 


The code expires in 24 hours. Didn’t try to sign up for Hotjar? You can safely ignore this email. 

Regards,
The Hotjar Team

**Comment by Israa91** [comment]
Sorry @maggiehoughton ,something went wrong , if you recieved now a new email can you send here please ,thanks.

**Comment by maggiehoughton** [comment]
Welcome!       To get started, please enter this code to confirm it’s you.    282159          The code expires in 24 hours. Didn’t try to sign up for Hotjar? You can   safely ignore this email.       Regards,   The Hotjar Team
--

**Comment by egasparini** [comment]
@Israa91 just checking if this is finalised so we can move it to done.

**Comment by cemalokten** [comment]
Hi @maggiehoughton I've used the 'SAML single sign-on' option for both '[UCdigital@hyde-housing.co.uk](mailto:UCdigital@hyde-housing.co.uk)' and '[CoLdigital@hyde-housing.co.uk](mailto:CoLdigital@hyde-housing.co.uk)' - If you're able to let me know the respective sign-in codes that have been sent to these address then I can get hotjar setup this morning. Thanks!

**Comment by maggiehoughton** [comment]
I haven't received anything in either inbox

**Comment by cemalokten** [comment]
> I haven't received anything in either inbox

Sorry, my mistake, I assumed they had been setup already, I've just signed up using  UCdigital@hyde-housing.co.uk.

Please check UCdigital@hyde-housing.co.uk for a verification code.

Ill do the same for COL once UCdigital@hyde-housing.co.uk is complete

**Comment by cemalokten** [comment]
@maggiehoughton perhaps it would be easier to have a call to get this setup, let me know if you rather meet to discuss. I am on gather all day if that works for you.

**Comment by maggiehoughton** [comment]
224948
