### ISSUE TITLE
Set up CoL app

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#56]
Set up CoL app (as duplicate of UC Helper) and strip away the content 

**Notes**
This will involve cloning the existing UC Helper repo. This entire tool is nearly entirely built on the existing UC helper functionality so we want to copy as much as possible :) 

- [x] Clone repo
- [x] Make Heroku project
- [x] Make Heroku database
- [x] Deploy to Heroku
- [x] Set up DNS records

**Comment by fadeomar** [comment]
we need to update the google analytics URL after finishing the deployment and get the real production link  
![image](https://user-images.githubusercontent.com/39485495/203806082-07678faa-1852-4357-85be-b0e6ade8cc76.png)

**Comment by remaininlight** [comment]
Currently debugging some package errors from deploying to Heroku. Setting up the buckets and IAM users for them using Terraform

**Comment by maggiehoughton** [comment]
HI Mark- the response I got from It was 

_We’ve registered it on cloudflare, it’s difficult to delegate to a third party dns.
If they tell us what records they want then we can add them._

So @RamyAlshurafa was going to provide me with the relevant details. Also happy to link yo guys to our IT directly if easier?

**Comment by remaininlight** [comment]
Thanks @maggiehoughton, I'm at mark@yallacooperative.com if that's easier. If they would set up the DNS as follows that would be grand:

Staging: CNAME hydecostoflivingstaging.herokudns.com
Production: CNAME hydecostofliving.herokudns.com

Do you know what domain names each of staging and production will be using please?

Hope your cold is improving!

**Comment by remaininlight** [comment]
Hi @maggiehoughton, in order for the encryption on the staging environment to work we need to upgrade the Heroku dyno plan to be the same as the production version

It's the same upgrade as what you did with Ramy for the production version, except for this app:
https://dashboard.heroku.com/apps/hydecostoflivingstaging/settings

Let me know if it's helpful for me to take you through it! I have a fairly flexible afternoon. Would be great if this could happen as soon as convenient for the demo tomorrow

**Comment by maggiehoughton** [comment]
Be great if you can talk me through it? I am free until 12:45 , and again after 3.

**Comment by remaininlight** [comment]
@maggiehoughton Great, I'm in Gather if you're free to join now?

**Comment by egasparini** [comment]
@Israa91 I see there's an open item for you on @RamyAlshurafa's comment here: https://github.com/yalla-coop/cost-of-living-support/issues/56#issuecomment-1330410597 
Can you please confirm if it's been done? 
Thanks!

**Comment by Israa91** [comment]
Hey @egasparini yes its done now.
