### ISSUE TITLE
Wireframes & Design System

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#67]
Scope of this task includes: 

- [x] Wireframes - First iteration
    - Build initial wireframes based on priority user journeys
    - Start creating the Design System
    - Changes: https://github.com/yalla-coop/cost-of-living-support/issues/67

- [x] Wireframes - Second iteration
   - Update wireframes based on user feedback
   - Finalise Design System

**Comment by jema28** [comment]
Hey @egasparini the typography styles and colour styles have now been updated 

Typography: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4601%3A21608
Colour: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4601%3A22021
- [ ] @fadeomar Gray 9 should be Neutral Main

**Comment by fadeomar** [comment]
hey @jema28, for Typography and Colors are these changes for both COL and hyde?

**Comment by fadeomar** [comment]
hey @jema28 for your note `Gray 9 should be Neutral Main`  we already have Neutral Main? 
```
export default {
  primaryMain,
  primaryMid: '#FDDDD7',
  primaryLight: '#FFF5F3',
  secondaryMain: '#3B557A',
  secondaryMid: '#4F6687',
  secondaryLight: '#F7FBFF',
  neutralMain: '#1A202B', <===========
  neutralPrimaryMVP: '#1A202C',
  neutralDark: '#5A666A',
  neutralMid: '#D9D6CC',
  neutralLight: '#F4F1E5',
  neutralSurface: '#FBF9F5',
  white: '#ffffff',
  modalBackground: '#255599b3',
  error: primaryMain,
  borderPrimary: primaryMain,
  borderSecondary: '#5A666A',
  gray9: '#3C404B', <=============
};

**Comment by jema28** [comment]
Hey @fadeomar I think add the new typography styles to both but not all will be used. For colours I think they're only needed to CoL. 

For gray9 can you change everything that is using gray9 currently to Neutral Main and then delete gray9 from the list
